server:
  port: 9797
  
spring:
  application:
    name: Zuul-Server
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
zuul:
  routes:
    flipkart:
      path: /flipkart-api/**       
      
      service-id: Shopping-Service

